### ISSUE TITLE
Error: Could not find or load main class ru.mihaly4.vkmd.Bootstrap

### ISSUE THREAD

**Issue by UksusoFF** [bupy7/java-vkmd#5]
```
C:\Windows\System32>D:\vkmd\bin\vkmd.bat
Error: Could not find or load main class ru.mihaly4.vkmd.Bootstrap
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Windows 8.1 
Java for Windows Version 8 Update 261 Release date July 14, 2020

**Comment by UksusoFF** [comment]
Successfully launched directly from jar file. 

But have trouble with download some audios. E.g. https://vk.com/wall-24564033_6360

**Comment by bupy7** [comment]
I will appreciate If you may debug it. Because on macOS everything is ok.

**Comment by UksusoFF** [comment]
Seems it's because I have installed multiple Java - OpenJRE and OracleJRE.
